### ISSUE TITLE
Enhancement: Functionality with Android TV

### ISSUE THREAD

**Issue by arraylabs** [happyleavesaoc/python-firetv#13]
Any thoughts on what it would take to get it working with Android TV (nvidia shield). I connected to my shield via adb and the "pm dump" and "am start" commands work and I can launch apps by package name from an adb shell via the network. Adding the device ip:port to firetvserver essentially stops it from working at all (the rest interface at least) but i don't get any errors in the console.

Thoughts, ideas on where to start? I already have a fork with the start/stop fixes by juliangeiges and the persistance changes as well.

Thanks!!

**Comment by juliangeiges** [comment]
@arraylabs When you checked it, do you still where connected to your shield manually? I`ve also seen this error (FireTV server stops from working at all) wenn there is allready one ADB connection to the Firetv.

**Comment by arraylabs** [comment]
@juliangeiges I haven't had too much time recently to continue working on it. But I'm not entirely convinced that I was "authorized" via ADB to to the shield. I know I was when the shield was connected to my desktop, but not sure it was when running in docker inside a virtual machine in VMware. So kinda stuck at that point and haven't thought of a brilliant way to get "authorized" in the vm docker. I will get back to it at some point especially now since the shield just got the playstation vue app. Thanks!

**Comment by arsaboo** [comment]
It seems we can run the same `adb` commands on Android TV, so should be relatively easy to extend this to Android TV. For example, on Android TV, the following works:
```
adb connect <ip address of Shield TV>
adb shell am start com.netflix.ninja/.MainActivity
```
Let me know if I can help you in extending this to Android TV (Shield TV).

**Comment by happyleavesaoc** [comment]
The shield is apparently running Android Kitkat, which requires authentication: https://github.com/google/python-adb#using-as-a-python-library

**Comment by jonasgrosch** [comment]
Hey, also owning the shield tv and i am very interested in this. Getting authentication error like you mentioned. Could you help me getting it work?

**Comment by fotiDim** [comment]
I tested with my Shield TV and almost everything works. I don't understand why this project is Fire TV branded. The only things that didn't work were `apps/running` and `<app_id>/stop` which might be due to new security policies or settings within developer options.

**Comment by JeffLIrion** [comment]
There are some differences between Fire TV and Android TV devices. Using this package as a starting point, I created the [androidtv](https://github.com/JeffLIrion/python-androidtv) package. Integration into HA is a work in progress; here is a recent iteration of the component: [androidtv.py](https://github.com/hassio-addons/addon-adb/blob/master/custom_components/media_player/androidtv.py).
