### ISSUE TITLE
FireTV Media Player not showing up in HASS

### ISSUE THREAD

**Issue by Nitee** [happyleavesaoc/python-firetv#14]
I got my FireTV setup using this guide: https://home-assistant.io/components/media_player.firetv/

However when I run the firetv-server it works fine when going to localhost and shows the proper state of my firetv, but I can't get Home Assistant to connect to it. I'm assuming this is due to the firetv server not starting at boot and rather me starting it up after boot?

Here is the error in homeassistant:

16-10-30 03:55:05 homeassistant.components.media_player.firetv: Could not connect to firetv-server at 192.168.1.202:5555

**Comment by Nitee** [comment]
So I got this solved, however the device is now showing improper states.

Whenever my firetv is in the main menu or paused video it shows "playing"

**Comment by happyleavesaoc** [comment]
Do you have a Fire TV stick or other device? What version of FireOS is it running? There is some variation out there.

**Comment by Nitee** [comment]
I'm running on a FireTV stick on OS: 5.2.2.0

**Comment by tringler** [comment]
How did you solve it? I have currently the same problem.

**Comment by Nitee** [comment]
@tringler What problem are you referring to?

@happyleavesaoc Have you been able to find possible fixes for this issue? It's not too big of a deal, but it kinda sucks since if I want to pause it and get out of bed it's kinda hard to see.

**Comment by tringler** [comment]
@Nitee I was able to solve it.

**Comment by Nitee** [comment]
@tringler Did you solve the issue with improper states or some other issue?

**Comment by JeffLIrion** [comment]
The original issue of integration with HA has been solved. Discussion of state detection should go in this issue: https://github.com/happyleavesaoc/python-firetv/issues/7.
