### ISSUE TITLE
latest version with -c arguement not on pip

### ISSUE THREAD

**Issue by stevenhorner** [happyleavesaoc/python-firetv#24]
Followed instructions to install and was wondering why the persistence option "-c" was not working but looks like the version installed via pip is from 2016-05-11.

Can this be updated rather than installing manually from github?

**Comment by happyleavesaoc** [comment]
It is coming to pip soonish. I need to figure out how to properly package it, since one of the dependencies is on github, not pypi.

**Comment by ChrisLechn** [comment]
Installed it from pip today and I'm still missing the -c option. Would be great if you could fix it. Great project by the way!

**Comment by Dirt-Nasty** [comment]
@ChrisLechn doesn't look like up he updated the pip version yet.  I am waiting as well.  @happyleavesaoc any other way we can run the newest version?

**Comment by ChrisLechn** [comment]
I've created a PHP script that add the devices after the service was started without configuration. Should be possible to run the script after the service was started automatically. Here's what I use.
`<?
//FireTV-Server Url
$url = 'http://xxx.xxx.xxx.xxx:5556/devices/add';
 
//Initiate cURL.
$ch = curl_init($url);
 
//The JSON data.
$jsonData = array(
    'device_id' => 'MyName',
    'host' => 'xxx.xxx.xxx.xxx:5555'
);
 
//Encode the array into JSON.
$jsonDataEncoded = json_encode($jsonData);
 
//Tell cURL that we want to send a POST request.
curl_setopt($ch, CURLOPT_POST, 1);
 
//Attach our encoded JSON string to the POST fields.
curl_setopt($ch, CURLOPT_POSTFIELDS, $jsonDataEncoded);
 
//Set the content type to application/json
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json')); 
 
//Execute the request
$result = curl_exec($ch);
echo $result;
?>`

**Comment by Dirt-Nasty** [comment]
@ChrisLechn sorry how do I execute the script?

**Comment by happyleavesaoc** [comment]
pypi now has `1.0.3`. Install with `pip install firetv[firetv-server] --process-dependency-links`

Let me know if that doesn't work.

**Comment by onerealfunnyguy** [comment]
Help, what am I missing.

root@ha:~# pip2 install firetv[firetv-server] --process-dependency-links
Downloading/unpacking firetv[firetv_server]
  Downloading firetv-1.0.3-py2-none-any.whl
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1266, in prepare_files
    req_to_install.extras):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2401, in requires
    dm = self._dep_map
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2597, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2621, in _compute_dependencies
    parsed = next(parse_requirements(distvers))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 49, in <lambda>
    next = lambda o: o.next()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2721, in parse_requirements
    "version spec")
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2697, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ("Expected ',' or end-of-list in", 'adb ==1.1.0+git.master', 'at', '+git.master')

**Comment by happyleavesaoc** [comment]
I pushed 1.0.4, try that one.

**Comment by onerealfunnyguy** [comment]
Thank you so mush, awesome component!

Successfully installed firetv adb
Cleaning up…

Had to install pyyaml

Thanks again!!

![screen shot 2017-01-06 at 4 36 58 pm](https://cloud.githubusercontent.com/assets/10824517/21737518/721bf924-d42e-11e6-8364-e2670bde6f2c.png)

**Comment by TheLerch** [comment]
Install works for me but I get errors when I use the following for a config file:

```
devices:
  gazebo:
    host: 10.50.254.49:5555
  livingroom:
    host: 10.50.254.50:5555
```

`root@cm0auto00:/home/pi# /usr/local/bin/firetv-server -c /home/hass/.homeassistant/firetv.yaml 
Traceback (most recent call last):
  File "/usr/local/bin/firetv-server", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/firetv/__main__.py", line 221, in main
    _add_devices_from_config(args)
  File "/usr/local/lib/python2.7/dist-packages/firetv/__main__.py", line 210, in _add_devices_from_config
    add(device, config['devices'][device]['host'])
  File "/usr/local/lib/python2.7/dist-packages/firetv/__main__.py", line 81, in add
    devices[device_id] = FireTV(str(host))
  File "/usr/local/lib/python2.7/dist-packages/firetv/__init__.py", line 51, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/firetv/__init__.py", line 64, in connect
    raise serr
socket.error: [Errno 104] Connection reset by peer`

**Comment by onerealfunnyguy** [comment]
can run firetv-server -d -ip:555 in docker works fine, 
yet firetv-server -d -c /usr/src/firetv/fire_tvs.yaml 
just hangs with out starting.

**Comment by sytone** [comment]
Custom docker or my docker container? I'm running fine with this. Change paths if on Linux.

docker run -d --restart=always -v F:/docker/firetv/config:/config --name python-firetv -p 5556:5556 sytone/python-firetv -c /config/house.yaml

**Comment by onerealfunnyguy** [comment]
Was building a custom image, which I can make work with 1 firth yet not the -c option, No luck with yours either, they run yet not able to open http://localhost:5556/devices/list (Docker on Mac) or http://hive:5556/devices/list (My debain docker server)

**Comment by onerealfunnyguy** [comment]
This works ever time: docker run -d --restart=always   --name python-firetv-1 -p 5556:5556 sytone/python-firetv -d 192.168.0.15:5555

When run like this can see it running in docker yet will not answer any web request, server down
docker run -d --restart=always -v /home/shortbus/firetv/config:/config --name python-firetv -p 5556:5556 sytone/python-firetv -c /config/house.yaml
My house.yaml
devices:
  ShortFire:
    host: 192.168.0.16:5555
  default:
    host: 192.168.0.15:5555
Thoughts?

**Comment by sytone** [comment]
Can you post your command line and files and I will try and reproduce

Tiny keyboard. Short responses. Do not read anything into it. Get Outlook<https://aka.ms/qtex0l> for iOS

________________________________

**Comment by onerealfunnyguy** [comment]
docker run -d --restart=always -v /home/shortbus/firetv/config:/config --name python-firetv -p 5556:5556 sytone/python-firetv -c /config/house.yaml
[Archive.zip](https://github.com/happyleavesaoc/python-firetv/files/819050/Archive.zip)

**Comment by JeffLIrion** [comment]
I think the original issue has been fixed. If there are other issues, please open a new issue.
