### ISSUE TITLE
pip git install of python-firetv wont complete

### ISSUE THREAD

**Issue by TheLerch** [happyleavesaoc/python-firetv#26]
I could not install using pip install directly so I tried:

`pip install git+https://github.com/happyleavesaoc/python-firetv`

This produced the following error and output:

`root@cm0auto00:~# pip install git+https://github.com/happyleavesaoc/python-firetv
Collecting git+https://github.com/happyleavesaoc/python-firetv
  Cloning https://github.com/happyleavesaoc/python-firetv to /tmp/pip-hRMgfg-build
    Complete output from command python setup.py egg_info:
    error in firetv setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-hRMgfg-build/
root@cm0auto00:~# `

**Comment by happyleavesaoc** [comment]
Pushed a new version, 1.0.4

**Comment by TheLerch** [comment]
Installed great and works for single instances.
