### ISSUE TITLE
Is there a way to install this on a HomeAssistant server running through windows

### ISSUE THREAD

**Issue by vdotk** [happyleavesaoc/python-firetv#27]
I have Home Assistant on a Windows machine-- is there a way to use this on windows?

Thank you!

**Comment by onerealfunnyguy** [comment]
https://www.youtube.com/watch?v=X27eVvuqwnY or https://home-assistant.io/getting-started/installation-docker/

**Comment by vdotk** [comment]
I have Home Assistant installed on windows-- I was curious if I can run python-firetv through windows

**Comment by onerealfunnyguy** [comment]
Install python 2 for windows and should be fine

**Comment by vdotk** [comment]
Really appreciate your replies...I'm having trouble getting past the first step  {swig libssl-dev python-dev libusb-1.0-0 } because I don't have access to apt-get on windows and pip isn't able to install whats needed

**Comment by onerealfunnyguy** [comment]
http://www.swig.org/Doc1.3/Windows.html
http://www.blogcompiler.com/2011/12/21/openssl-for-windows/
https://sourceforge.net/projects/tdm-gcc/files/Sources/Vanilla%20Sources/_Deprecated/python-dev/
https://github.com/libusb/libusb/wiki/Windows

And the faster route is https://forums.virtualbox.org/viewtopic.php?f=9&t=62452
And a Debain VM running home-assistant & the firetv server with a second VM running ZoneMinder are what I am using running on a windows7 box.

**Comment by vdotk** [comment]
Thanks...I was trying to avoid VM, but looking at everything--it seems it will actually be easier. Thanks for your replies.
