### ISSUE TITLE
No FIreTV entities showing in HA 38.2 running latest version of server

### ISSUE THREAD

**Issue by rpitera** [happyleavesaoc/python-firetv#29]
Running 1.0.5 version of firetv-server on RasPi@192.168.1.181.  Two FireTV boxes, both have ADB/USB debugging on, in same network.  (pyyaml installed manually so I could use the -c option)  Server loads without an error.

firetv-server config file:
```
devices:
  bedroom:
    host: 192.168.1.166:5555
  livingroom:
    host: 192.168.1.173:5555
```
Verify devices at 192.168.1.181:5556 works and shows the following:
```
{
  "devices": {
    "bedroom": {
      "host": "192.168.1.166:5555", 
      "state": "off"
    }, 
    "livingroom": {
      "host": "192.168.1.173:5555", 
      "state": "idle"
    }
  }
}
```
All states in update as expected in the browser when changed at the device.  (State shown above is correct, livingroom device is currently paused and at the screen saver.)

Config in media_players.yaml (included properly as other media_players showing up fine):
```
- platform: firetv
    entity_namespace: 'ftv'
    host: 192.168.1.181
    port: 5556
```
No errors at all in the HA logs.  Completely clear.  Discovery is enabled.

Absolutely nothing is showing up in dev states panel for any FireTV media_players.

I'm pulling my hair out here because I can't think of anything else that I may have missed.  Gone over every post in the forums as well as issues here.  No errors in any logs.

Any idea what I may have missed?

**Comment by rpitera** [comment]
Also Pi is running Python 2.7.9
HA is in a venv

**Comment by rpitera** [comment]
Now seeing some errors related to FireTV showing up (prior to this there were none):

```
17-02-19 11:28:04 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up platform firetv
Traceback (most recent call last):
  File "/srv/hass/hass_venv/lib/python3.4/site-packages/homeassistant/helpers/entity_component.py", line 151, in _async_setup_platform
    entity_platform.add_entities, discovery_info
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/hass/hass_venv/lib/python3.4/site-packages/homeassistant/components/media_player/firetv.py", line 52, in setup_platform
    response = requests.get(DEVICE_LIST_URL.format(host, port)).json()
  File "/srv/hass/hass_venv/lib/python3.4/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

Any kind of response here would be appreciated.

**Comment by JeffLIrion** [comment]
I'm closing this issue because the HA component now uses this package directly, rather than indirectly through the `firetv-server`.
