### ISSUE TITLE
Emulate select button, directional buttons

### ISSUE THREAD

**Issue by b1gbake** [happyleavesaoc/python-firetv#39]
Is there any way to emulate the select button or directional keys of the firetv remote? I can launch an app, and the first tile that is highlighted is the live tv selection. I would like to have a script that launches the app, then after a delay emulate as if the select button had been pressed on the remote. This would launch the live tv portion of that app without any interaction with the remote. 

app is HGTV (tv.accedo.hgtv)
running hass 0.50.2
just got firetv-server up and running last night. everything seems to be working correctly.

**Comment by rytilahti** [comment]
The library supports this already (see `right()`, `left()`, `up()`, `down()` and `enter()`), they are not just hooked anyway in homeassistant. Please consider reporting the bug in homeassistant and closing this.

**Comment by b1gbake** [comment]
My apologies. I only looked at the readme. I looked over the code and see I can request the other actions. They aren't all listed in the readme. Noob mistake. Thank your for pointing that out @rytilahti 


They don't need to be tied into HASS really, I'm using them as shell commands. I will tie them into a script with delays to get the desired action. Thanks for the excellent work @happyleavesaoc
