### ISSUE TITLE
HDHomeRun Support

### ISSUE THREAD

**Issue by stingray67** [happyleavesaoc/python-firetv#42]
Hi,

I received the standard 404 error when sending app open commands for the HDHomeRun app. I traced the program name and cmp activity, and tried multiple combos. I then issued the following on my computer and I was able to open up the HDHomeRun app on my AFTV:

"ssh shell am start -n com.silicondust.view/.MediaCodecPlayer"

I have a subprocess running, and I'm confused on how I can pass that adb command. I imagine it's a simple one-liner, but I'm no expert. I think it sounds like I need to pass this adb command to 127.0.0.1, but I do not know how to do it. 

Thanks for your help

**Comment by JeffLIrion** [comment]
```python
ftv = FireTV(...)
ftv.adb_shell("am start -n com.silicondust.view/.MediaCodecPlayer")
```
