### ISSUE TITLE
Getting error when trying to start server, either with IP or without

### ISSUE THREAD

**Issue by jolaroux** [happyleavesaoc/python-firetv#44]
(my_project) pi@raspberrypi:~/my_project $ firetv-server -d 192.168.1.119:5555

Traceback (most recent call last):
  File "/usr/local/bin/firetv-server", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: libusb1>=1.0.16
(my_project) pi@raspberrypi:~/my_project $ 

This is the error I keep getting. installing on fresh 2.7 virtual environment on my raspberry pi.

**Comment by jolaroux** [comment]
can this server be run NOT using hassbian? I installed HA in a python venv on my rpi. I can't install hassbian because I have other servers running in my pi, I can't flash the whole pi to just do this. 

Is this not possible?

**Comment by happyleavesaoc** [comment]
`firetv` has nothing to do with hassbian. You can certainly run them separately.

Anyway, you are missing the `libusb` dependency. Check the `Installation` section of the readme.

**Comment by jolaroux** [comment]
That's good to know! thanks for the response.

And when I run `sudo apt-get install swig libssl-dev python-dev libusb-1.0-0` from the readme,

I get: 
`(my_project) pi@raspberrypi:~/my_project $ sudo apt-get install swig libssl-dev python-dev libusb-1.0-0`
`Reading package lists... Done`
`Building dependency tree`
`Reading state information... Done`
`...`
`libusb-1.0-0 is already the newest version.`
`...`

So it seems that libusb is already installed which is weird.

**Comment by jolaroux** [comment]
Sorry to be a pain! I could start over in a new virtual environment and copy paste the whole terminal output if that would help diagnose what's going on

**Comment by JeffLIrion** [comment]
The package requirements have been updated. If you still get this error with the latest version, please reopen this issue or create a new one.
