### ISSUE TITLE
Can't connect, no matter what.

### ISSUE THREAD

**Issue by abuttino** [happyleavesaoc/python-firetv#46]
Here is a log of where I try to do a -d. 

It just will not connect.

https://pastebin.com/KiLFqjXa

Running on rPi Raspbian Stretch on a ZeroW. Followed all the directions to a T. Tested ADB with another PC and it's working tip top.

**Comment by Aareon** [comment]
Link is no longer valid. Please paste here directly.

**Comment by JeffLIrion** [comment]
Since there's no info about this issue, I'm going to close it. If it hasn't been resolved, feel free to reopen it or create a new one.
