### ISSUE TITLE
Device authentication required, no keys available

### ISSUE THREAD

**Issue by killadm** [happyleavesaoc/python-firetv#49]
> DEBUG:root:Connecting to device "192.168.123.97:5555"
Traceback (most recent call last):
  File "/usr/local/bin/firetv-server", line 11, in <module>
    load_entry_point('firetv==1.0.5', 'console_scripts', 'firetv-server')()
  File "/usr/local/lib/python2.7/dist-packages/firetv/__main__.py", line 249, in main
    _add_devices_from_config(args)
  File "/usr/local/lib/python2.7/dist-packages/firetv/__main__.py", line 229, in _add_devices_from_config
    add(device, config['devices'][device]['host'])
  File "/usr/local/lib/python2.7/dist-packages/firetv/__main__.py", line 84, in add
    devices[device_id] = FireTV(str(host))
  File "/usr/local/lib/python2.7/dist-packages/firetv/__init__.py", line 61, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/firetv/__init__.py", line 72, in connect
    serial=self.host)
  File "/usr/local/lib/python2.7/dist-packages/adb/adb_commands.py", line 76, in ConnectDevice
    return cls.Connect(handle, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/adb/adb_commands.py", line 99, in Connect
    device_state = cls.protocol_handler.Connect(usb, banner=banner, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/adb/adb_protocol.py", line 288, in Connect
    'Device authentication required, no keys available.')
adb.usb_exceptions.DeviceAuthError: Device authentication required, no keys available.

I’m having the same issue:
https://community.home-assistant.io/t/firetv-server-component-adb-error/38546

 pi@raspberrypi:~ $ adb connect 192.168.123.97
 daemon not running. starting it now on port 5037 *
daemon started successfully *
connected to 192.168.123.97:5555

**Comment by waza-ari** [comment]
Yeah, one more here. Having the same problems as well. If you have any idea or need anything to help troubleshooting, please let me know

**Comment by happyleavesaoc** [comment]
FireTV devices running KitKat or greater require keys. We don't support that yet, but it would be simple for someone with such a device to add support. Take a look at the basic example here: https://github.com/google/python-adb#using-as-a-python-library

**Comment by blamas1** [comment]
I'm so glad I'm not the only person having this issue. I'm such a novice (didn't know python or yaml existed until last week) deciphering anything takes daaaays. I'd like to stay with this add-on so happy to wait. I'm brand new here so if this is rude or not allowed please ignore/delete. Is there an eta on this? Thank you so much!

**Comment by ghost** [comment]
any ideas when this might be supported?

**Comment by jibbajabber** [comment]
> FireTV devices running KitKat or greater require keys. We don't support that yet, but it would be simple for someone with such a device to add support. Take a look at the basic example here: https://github.com/google/python-adb#using-as-a-python-library

Confirmed working. Many thanks.

For the benefit of others, overriding FireTV connect with the following should work (after trust has been established (assuming this is what creates adbkey)). This will need adb.sign_m2crypto and os.path as:
``` python
from adb import sign_m2crypto
import os.path as op

def connect(self):
        """ Connect to an Amazon Fire TV device.

        Will attempt to establish ADB connection to the given host.
        Failure sets state to DISCONNECTED and disables sending actions.
        """
        try:
            # KitKat+ devices require authentication
            signer = sign_m2crypto.M2CryptoSigner(
                op.expanduser('~/.android/adbkey'))
            # Connect to the device
            device = adb_commands.AdbCommands()
            self._adb = device.ConnectDevice(serial=self.host, rsa_keys=[signer])
        except socket_error as serr:
            print 'Exception raised'
            if serr.errno != errno.ECONNREFUSED:
                raise serr
```
I guess sub-classing or some deterministic approach in connect would need to be made to differentiate between KitKat and pre KitKat devices, to make this viable for a patch or MR.

**Comment by MarvAmBass** [comment]
@happyleavesaoc would be nice to implement @jibbajabber's solution into your master. But it only uses the signer when the `adbkey` file is found. Would this be possible?

Thanks

Maybe someone likes this whole fixed thing as a dockercontainer (https://github.com/MarvAmBass/docker-firetv-server)
