### ISSUE TITLE
Cannot get firetv-server or firetv to install from pip

### ISSUE THREAD

**Issue by acordill** [happyleavesaoc/python-firetv#59]
firetv@raspberrypi:~ $pip install firetv[firetv-server]
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting firetv[firetv-server]
  Downloading https://files.pythonhosted.org/packages/78/f8/ec97e02ae8102ece206f3cf08643d10ba7cc8b9ab7a3d5855040804583e3/firetv-1.0.5.tar.gz
Collecting adb>=1.1.0 (from firetv[firetv-server])
  Downloading https://files.pythonhosted.org/packages/39/c0/715acc4e0c37a6a93f73daf8536baea94ac9fb6539ef1fd9c42205e1c3fa/adb-1.3.0-py2-none-any.whl
Requirement already satisfied: Flask>=0.10.1 in ./firetv/lib/python2.7/site-packages (from firetv[firetv-server]) (1.0.2)
Collecting PyYAML>=3.12 (from firetv[firetv-server])
  Downloading https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz (270kB)
    100% |████████████████████████████████| 276kB 3.7MB/s 
Collecting M2Crypto<=0.26.4,>=0.21.1 (from adb>=1.1.0->firetv[firetv-server])
  Downloading https://files.pythonhosted.org/packages/dc/5b/1ff81e2dda5d2dee62d1c26f5df91b1ea3a560b6611cea67e6c55d1f2e15/M2Crypto-0.26.4.tar.gz (1.1MB)
    100% |████████████████████████████████| 1.1MB 2.7MB/s 
Collecting libusb1>=1.0.16 (from adb>=1.1.0->firetv[firetv-server])
  Downloading https://files.pythonhosted.org/packages/ec/5d/4fdac6c53525786fe35cff035c3345452e24e2bee5627893be65d12555cb/libusb1-1.6.4.tar.gz (55kB)
    100% |████████████████████████████████| 61kB 1.6MB/s 
Requirement already satisfied: click>=5.1 in ./firetv/lib/python2.7/site-packages (from Flask>=0.10.1->firetv[firetv-server]) (6.7)
Requirement already satisfied: Werkzeug>=0.14 in ./firetv/lib/python2.7/site-packages (from Flask>=0.10.1->firetv[firetv-server]) (0.14.1)
Requirement already satisfied: itsdangerous>=0.24 in ./firetv/lib/python2.7/site-packages (from Flask>=0.10.1->firetv[firetv-server]) (0.24)
Requirement already satisfied: Jinja2>=2.10 in ./firetv/lib/python2.7/site-packages (from Flask>=0.10.1->firetv[firetv-server]) (2.10)
Collecting typing (from M2Crypto<=0.26.4,>=0.21.1->adb>=1.1.0->firetv[firetv-server])
  Downloading https://files.pythonhosted.org/packages/0d/4d/4e5985d075d241d686a1663fa1f88b61d544658d08c1375c7c6aac32afc3/typing-3.6.4-py2-none-any.whl
Requirement already satisfied: MarkupSafe>=0.23 in ./firetv/lib/python2.7/site-packages (from Jinja2>=2.10->Flask>=0.10.1->firetv[firetv-server]) (1.0)
Building wheels for collected packages: firetv, PyYAML, M2Crypto, libusb1
  Running setup.py bdist_wheel for firetv ... done
  Stored in directory: /home/firetv/.cache/pip/wheels/06/92/a6/a1ee80fdb15392919a33a57f404e03238db1f119587dd596e5
  Running setup.py bdist_wheel for PyYAML ... done
  Stored in directory: /home/firetv/.cache/pip/wheels/ad/da/0c/74eb680767247273e2cf2723482cb9c924fe70af57c334513f
  Running setup.py bdist_wheel for M2Crypto ... error
  Complete output from command /home/firetv/firetv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-XVZVug/M2Crypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-9Hewwh --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  copying M2Crypto/six.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/RSA.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/Err.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/DH.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/Rand.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/m2.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/callback.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/util.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/EVP.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/RC4.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/ASN1.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/m2xmlrpclib.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/httpslib.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/SMIME.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/DSA.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/__init__.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/BIO.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/X509.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/EC.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/m2urllib.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/m2crypto.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/Engine.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/ftpslib.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/BN.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/threading.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/m2urllib2.py -> build/lib.linux-armv7l-2.7/M2Crypto
  copying M2Crypto/AuthCookie.py -> build/lib.linux-armv7l-2.7/M2Crypto
  creating build/lib.linux-armv7l-2.7/M2Crypto/PGP
  copying M2Crypto/PGP/PublicKey.py -> build/lib.linux-armv7l-2.7/M2Crypto/PGP
  copying M2Crypto/PGP/packet.py -> build/lib.linux-armv7l-2.7/M2Crypto/PGP
  copying M2Crypto/PGP/RSA.py -> build/lib.linux-armv7l-2.7/M2Crypto/PGP
  copying M2Crypto/PGP/constants.py -> build/lib.linux-armv7l-2.7/M2Crypto/PGP
  copying M2Crypto/PGP/__init__.py -> build/lib.linux-armv7l-2.7/M2Crypto/PGP
  copying M2Crypto/PGP/PublicKeyRing.py -> build/lib.linux-armv7l-2.7/M2Crypto/PGP
  creating build/lib.linux-armv7l-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/SSLServer.py -> build/lib.linux-armv7l-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/Checker.py -> build/lib.linux-armv7l-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/Cipher.py -> build/lib.linux-armv7l-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/timeout.py -> build/lib.linux-armv7l-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/Connection.py -> build/lib.linux-armv7l-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/__init__.py -> build/lib.linux-armv7l-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/cb.py -> build/lib.linux-armv7l-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/Context.py -> build/lib.linux-armv7l-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/Session.py -> build/lib.linux-armv7l-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/ssl_dispatcher.py -> build/lib.linux-armv7l-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/TwistedProtocolWrapper.py -> build/lib.linux-armv7l-2.7/M2Crypto/SSL
  running build_ext
  building 'M2Crypto._m2crypto' extension
  swigging SWIG/_m2crypto.i to SWIG/_m2crypto_wrap.c
  swig -python -D__armv7l__ -I/usr/include/python2.7 -I/usr/include -I/usr/include/arm-linux-gnueabihf -includeall -modern -builtin -outdir /tmp/pip-install-XVZVug/M2Crypto/M2Crypto -o SWIG/_m2crypto_wrap.c SWIG/_m2crypto.i
  /usr/include/arm-linux-gnueabihf/gnu/stubs.h:7: Error: Unable to find 'gnu/stubs-soft.h'
  error: command 'swig' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for M2Crypto
  Running setup.py clean for M2Crypto
  Running setup.py bdist_wheel for libusb1 ... done
  Stored in directory: /home/firetv/.cache/pip/wheels/98/8d/8b/bac0a20eb9757e7dbf46e8ab1f1695c78ad919f53080a58bc1
Successfully built firetv PyYAML libusb1
Failed to build M2Crypto
Installing collected packages: typing, M2Crypto, libusb1, adb, PyYAML, firetv
  Running setup.py install for M2Crypto ... error
    Complete output from command /home/firetv/firetv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-XVZVug/M2Crypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-Psnwge/install-record.txt --single-version-externally-managed --compile --install-headers /home/firetv/firetv/include/site/python2.7/M2Crypto:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-2.7
    creating build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/six.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/RSA.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/Err.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/DH.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/Rand.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/m2.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/callback.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/util.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/EVP.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/RC4.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/ASN1.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/m2xmlrpclib.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/httpslib.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/SMIME.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/DSA.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/__init__.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/BIO.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/X509.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/EC.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/m2urllib.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/m2crypto.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/Engine.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/ftpslib.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/BN.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/threading.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/m2urllib2.py -> build/lib.linux-armv7l-2.7/M2Crypto
    copying M2Crypto/AuthCookie.py -> build/lib.linux-armv7l-2.7/M2Crypto
    creating build/lib.linux-armv7l-2.7/M2Crypto/PGP
    copying M2Crypto/PGP/PublicKey.py -> build/lib.linux-armv7l-2.7/M2Crypto/PGP
    copying M2Crypto/PGP/packet.py -> build/lib.linux-armv7l-2.7/M2Crypto/PGP
    copying M2Crypto/PGP/RSA.py -> build/lib.linux-armv7l-2.7/M2Crypto/PGP
    copying M2Crypto/PGP/constants.py -> build/lib.linux-armv7l-2.7/M2Crypto/PGP
    copying M2Crypto/PGP/__init__.py -> build/lib.linux-armv7l-2.7/M2Crypto/PGP
    copying M2Crypto/PGP/PublicKeyRing.py -> build/lib.linux-armv7l-2.7/M2Crypto/PGP
    creating build/lib.linux-armv7l-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/SSLServer.py -> build/lib.linux-armv7l-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/Checker.py -> build/lib.linux-armv7l-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/Cipher.py -> build/lib.linux-armv7l-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/timeout.py -> build/lib.linux-armv7l-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/Connection.py -> build/lib.linux-armv7l-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/__init__.py -> build/lib.linux-armv7l-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/cb.py -> build/lib.linux-armv7l-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/Context.py -> build/lib.linux-armv7l-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/Session.py -> build/lib.linux-armv7l-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/ssl_dispatcher.py -> build/lib.linux-armv7l-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/TwistedProtocolWrapper.py -> build/lib.linux-armv7l-2.7/M2Crypto/SSL
    running build_ext
    building 'M2Crypto._m2crypto' extension
    swigging SWIG/_m2crypto.i to SWIG/_m2crypto_wrap.c
    swig -python -D__armv7l__ -I/usr/include/python2.7 -I/usr/include -I/usr/include/arm-linux-gnueabihf -includeall -modern -builtin -outdir /tmp/pip-install-XVZVug/M2Crypto/M2Crypto -o SWIG/_m2crypto_wrap.c SWIG/_m2crypto.i
    /usr/include/arm-linux-gnueabihf/gnu/stubs.h:7: Error: Unable to find 'gnu/stubs-soft.h'
    error: command 'swig' failed with exit status 1
    
    ----------------------------------------
Command "/home/firetv/firetv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-XVZVug/M2Crypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-Psnwge/install-record.txt --single-version-externally-managed --compile --install-headers /home/firetv/firetv/include/site/python2.7/M2Crypto" failed with error code 1 in /tmp/pip-install-XVZVug/M2Crypto/

**Comment by nnhhuu** [comment]
i'm having the same error ... is there any solution for that

**Comment by JeffLIrion** [comment]
This is fixed in 1.0.7.
