### ISSUE TITLE
Cannot find adb=1.3.0.dev for Docker installation

### ISSUE THREAD

**Issue by mmotley999** [happyleavesaoc/python-firetv#63]
I've had this working beautifully with an older version of firetv-server.  But then my firetv updated, and I'm getting the "missing key" issue.  I see the latest version added an 'adbkey' property.

However, building the latest version with Docker results in this:

```
Collecting adb==1.3.0.dev (from firetv==1.0.5.dev0)
  Could not find a version that satisfies the requirement adb==1.3.0.dev (from firetv==1.0.5.dev0) (from versions: 1.1.1, 1.2.0, 1.3.0)
No matching distribution found for adb==1.3.0.dev (from firetv==1.0.5.dev0)
The command '/bin/sh -c pip install /tmp/python-firetv-master[firetv-server] --process-dependency-links' returned a non-zero code: 1
```

I'm on a Raspberry Pi 3 with a modified Dockerfile (required for the base image, and previous versions of M2Cyrpto don't compile on this platform):

```
FROM arm32v7/python:2.7.13-stretch

RUN apt-get update && apt-get install -y \
        libssl-dev \
        libusb-1.0-0 \
        python-dev \
        swig \
        curl \
        unzip \
        && curl -L -o /tmp/master.zip https://github.com/happyleavesaoc/python-firetv/archive/master.zip \
        && cd /tmp \
        && unzip master.zip \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip --no-cache-dir install --upgrade pip
RUN pip --no-cache-dir install flask
RUN pip --no-cache-dir install https://pypi.python.org/packages/01/bd/a41491718f9e2bebab015c42b5be7071c6695acfa301e3fc0480bfd6a15b/M2Crypto-0.27.0.tar.gz
RUN pip install /tmp/python-firetv-master[firetv-server] --process-dependency-links

VOLUME ["/config"]

CMD ["firetv-server", "-c", "/config/devices.yaml"]
```

Tried adding a "RUN pip --no-cache install adb" before the main install of python-firetv-master, but that has a require for a previous version of M2Crypto (0.26.4) which, again, won't compile (hard vs soft float).

Any ideas?

**Comment by JeffLIrion** [comment]
I added the ADB key functionality and Python 3 compatibility to this `firetv` package, but in doing so I needed to make some changes to the `adb` package (I've got a pull request that's waiting to be merged -- https://github.com/google/python-adb/pull/119).  

The short answer to this issue is to use my custom component: https://github.com/JeffLIrion/homeassistant_native_firetv

**Comment by mmotley999** [comment]
@JeffLIrion, thanks!  I just installed it (homeassistant 0.76 manually installed on Raspbian), and it seems to work really well!

**Comment by JeffLIrion** [comment]
This issue is fixed in https://github.com/happyleavesaoc/python-firetv/commit/dae0f5ab805bbb214c4c2aea4a3433ec441240e8 and can be closed.
