### ISSUE TITLE
adb Connect Error

### ISSUE THREAD

**Issue by aravorn6** [happyleavesaoc/python-firetv#64]
starting the firetvserver with arguments -d ip:port I got this error: 

```
    self._adb = adb_commands.AdbCommands().ConnectDevice(serial=self.host)
TypeError: __init__() takes exactly 3 arguments (1 given)
```
using the latest git version for firetv and adb

**Comment by JeffLIrion** [comment]
This issue is fixed in https://github.com/happyleavesaoc/python-firetv/commit/91cd951a92cd8dee9a994e117db7e5e8bbb0f112
