### ISSUE TITLE
Cannot find firestick device

### ISSUE THREAD

**Issue by giacomotontini** [happyleavesaoc/python-firetv#67]
I followed the installation readme but this error persists. What am I missing?

`pi@raspberrypi:~ $ sudo firetv-server -d 192.168.0.12:5555`
`WARNING:root:Couldn't connect to host: 192.168.0.12:5555, error: None`

The device is reachable if I use adb connect 192.168.0.12 from windows shell

**Comment by jspeckman** [comment]
I am also having this same issue.

**Comment by dderichswei** [comment]
me too....

**Comment by giacomotontini** [comment]
Update for all those who installed this package to integrate a firestick device with home assistant: this is no longer needed since the latest HomeAssistant Update. The problem was caused by an Amazon update to our devices requiring a new procedure to guarantee security (adbkey handshake).
First of all, update home assistant to version 0.83.0, in the end follow that guide and everything should work fine: [FireTV HomeAssistant component](https://www.home-assistant.io/components/media_player.firetv/)

**Comment by jspeckman** [comment]
I'm not using python-firetv with HomeAssistant, so this issue is still a problem for me.

Update:  I missed the part about having to accept the connection on the firetv itself.
Everything is working fine now with python-adb and python3.

Thanks!

**Comment by joachimpr** [comment]
> I'm not using python-firetv with HomeAssistant, so this issue is still a problem for me.
> 
> Update: I missed the part about having to accept the connection on the firetv itself.
> Everything is working fine now with python-adb and python3.
> 
> Thanks!

How do you accept the connection on the FireTV device? I run the same command as above and get the same error. I don't however see anything popping up on the fire TV 4k stick?
