### ISSUE TITLE
`androidtv` integration

### ISSUE THREAD

**Issue by JeffLIrion** [happyleavesaoc/python-firetv#83]
@happyleavesaoc I'd like to combine your `firetv` package and my [`androidtv`](https://github.com/JeffLIrion/python-androidtv) package. Since `firetv` was the original package, I propose that we use your repository but we rename the package from `firetv` to `androidtv`, since Fire TVs are Android TVs but the reverse is not always true. Alternatively, I could integrate the `firetv` functionality into my `androidtv` repo and package. 

Please let me know how you'd like to proceed.

**Comment by happyleavesaoc** [comment]
That seems reasonable to me. Feel free to use either repository as a basis, I have no particular opinion.

**Comment by JeffLIrion** [comment]
Thanks!
