### ISSUE TITLE
Implement Persistence

### ISSUE THREAD

**Issue by juliangeiges** [happyleavesaoc/python-firetv#9]
What do you think about implementing some persistence? Adding different Fire TV Devices every reboot needs a lot of automation in my HA-System.

**Comment by happyleavesaoc** [comment]
What about a config file? Run the server like `firetv-server -c my_config.yaml`, where the config has a list of devices to be added at startup. If a device is added that isn't already in the config, it could be written to the config automatically.

Is that the sort of thing you're thinking of?

**Comment by juliangeiges** [comment]
yes exactly it is. If we still want to use the post route we should implement a persistence flag attribute which means: add it to the config file. But then we also need some delete route.
Or we keep it simple and only way to add devices with persistence is editing the yaml file.

**Comment by happyleavesaoc** [comment]
I would support such an enhancement, in simple or comprehensive form. I'm not sure when I'd be able to write it though. A PR would be certainly welcome.

**Comment by juliangeiges** [comment]
All Right, i will see if my python is good enough to do so and i`ve i have time on the weekend.
Can you provide me some starting points with parsing yaml on python? I am coming from Ruby... :)

**Comment by happyleavesaoc** [comment]
Yep, `pip install yaml`, then `import yaml`. Then you can `yaml.load(...)` to load from YAML to a python object, and `yaml.dump(...)` to go the other way. That's about all you need.

Full docs here: http://pyyaml.org/wiki/PyYAMLDocumentation

**Comment by kdvlr** [comment]
Not sure if it is relevant. Config would be the ideal approach, but I am currently using curl to add my devices at startup and it works fairly well 

`curl -X POST -H 'Content-Type:application/json' -H 'Accept: application/json' --data-binary @/home/hass/FamilyRoom.json http://localhost:5556/devices/add`

--FamilyRoom.json
{
  "device_id": "FamilyRoom",  "host": "192.169.1.12:5555"
}

**Comment by juliangeiges** [comment]
@kdvlr nice quick solution :) 
@happyleavesaoc thanks for your advice, i will do my best :)
